telegram:
  chatId: "chatId"
  apiToken: "apiToken"
commonTemplate: >
  [#{{ .Error.App.ReleaseStage }}, #{{ .Error.App.Type }}, {{ .Trigger.Message }}]

  Message: {{ .Error.Message }}

  URL: {{ .Error.URL }}
triggers:
  firstException:
    template: >
      [#{{ .Error.App.ReleaseStage }}, #{{ .Error.App.Type }}, {{ .Trigger.Message }}]

      Message: {{ .Error.Message }}

      URL: {{ .Error.URL }}
