telegram:
  chatId: "chatId"
  apiToken: "apiToken"
triggers:
  firstException:
    enabled: true
    template: >
      First Exception for {{ response.Account.Name }} company
  errorEventFrequency:
    enabled: true
    template: >
      First Exception for {{ response.Account.Name }} company
  powerTen:
    enabled: true
    template: >
      First Exception for {{ response.Account.Name }} company
  exception:
    enabled: true
    template: >
      First Exception {{ .Account.ID }}
  reopened:
    enabled: true
    template: >
      First Exception for {{ response.Account.Name }} company
  projectSpiking:
    enabled: true
    template: >
      First Exception for {{ response.Account.Name }} company
  release:
    enabled: true
    template: >
      First Exception for {{ response.Account.Name }} company
  projectSamplingStarted:
    enabled: true
    template: >
      First Exception for {{ response.Account.Name }} company
  projectApproachingRateLimit:
    enabled: true
    template: >
      First Exception for {{ response.Account.Name }} company
  comment:
    enabled: true
    template: >
      First Exception for {{ response.Account.Name }} company
  errorStateManualChange:
    enabled: true
    template: >
      First Exception for {{ response.Account.Name }} company
